print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/luishinostroza/unityProjects/First Unity Game/Assets/Objects/Bridge-01/bridge_01.mb"`)
{		
	file -o "/Users/luishinostroza/unityProjects/First Unity Game/Assets/Objects/Bridge-01/bridge_01.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/luishinostroza/unityProjects/First Unity Game/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/luishinostroza/unityProjects/First Unity Game/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/luishinostroza/unityProjects/First Unity Game/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
